-- 001_init.sql
-- Port of the original SQLite schema. Table and column names are unchanged.
--
-- Type mapping:
--   INTEGER PRIMARY KEY AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--   TEXT (dates)                      -> TEXT, kept in the same 'YYYY-MM-DD HH:MM:SS'
--                                        UTC format SQLite produced, so the admin
--                                        UI keeps rendering them unchanged
--   datetime('now')                   -> app_now()
--   PRAGMA journal_mode = WAL         -> not applicable (PostgreSQL has WAL natively)
--   PRAGMA foreign_keys = ON          -> always enforced in PostgreSQL

-- Replaces SQLite's datetime('now'): UTC, second precision, no timezone suffix.
CREATE OR REPLACE FUNCTION app_now() RETURNS text
  LANGUAGE sql VOLATILE AS $$
    SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');
  $$;

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name     TEXT NOT NULL DEFAULT '',
  username      TEXT NOT NULL UNIQUE,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'master' CHECK (role IN ('super_admin', 'master')),
  permissions   TEXT NOT NULL DEFAULT '[]',
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL DEFAULT app_now()
);

CREATE TABLE IF NOT EXISTS master_applications (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name         TEXT NOT NULL,
  phone             TEXT NOT NULL DEFAULT '',
  email             TEXT NOT NULL,
  username          TEXT NOT NULL,
  password_hash     TEXT NOT NULL,
  specialty         TEXT NOT NULL,
  message           TEXT NOT NULL DEFAULT '',
  status            TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  rejection_reason  TEXT NOT NULL DEFAULT '',
  created_at        TEXT NOT NULL DEFAULT app_now(),
  reviewed_at       TEXT,
  reviewed_by       INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS services (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  benefits    TEXT NOT NULL DEFAULT '',
  image       TEXT NOT NULL DEFAULT '',
  icon        TEXT NOT NULL DEFAULT 'wrench',
  price       TEXT NOT NULL DEFAULT '',
  sort_order  INTEGER NOT NULL DEFAULT 0,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT app_now()
);

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS media (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename      TEXT NOT NULL UNIQUE,
  original_name TEXT NOT NULL DEFAULT '',
  mime          TEXT NOT NULL DEFAULT '',
  size          INTEGER NOT NULL DEFAULT 0,
  object_key    TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL DEFAULT app_now()
);

CREATE TABLE IF NOT EXISTS sessions (
  token_id   TEXT PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT app_now(),
  expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS work_logs (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  master_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title          TEXT NOT NULL,
  customer_name  TEXT NOT NULL DEFAULT '',
  customer_phone TEXT NOT NULL DEFAULT '',
  car_brand      TEXT NOT NULL DEFAULT '',
  car_model      TEXT NOT NULL DEFAULT '',
  car_number     TEXT NOT NULL DEFAULT '',
  service_type   TEXT NOT NULL DEFAULT 'Diagnostika',
  description    TEXT NOT NULL DEFAULT '',
  start_date     TEXT NOT NULL DEFAULT '',
  end_date       TEXT NOT NULL DEFAULT '',
  price          REAL NOT NULL DEFAULT 0,
  status         TEXT NOT NULL DEFAULT 'Jarayonda' CHECK (status IN ('Jarayonda', 'Tugallangan')),
  is_public      INTEGER NOT NULL DEFAULT 0,
  notes          TEXT NOT NULL DEFAULT '',
  created_at     TEXT NOT NULL DEFAULT app_now(),
  updated_at     TEXT NOT NULL DEFAULT app_now()
);

CREATE TABLE IF NOT EXISTS work_log_images (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_log_id       INTEGER NOT NULL REFERENCES work_logs(id) ON DELETE CASCADE,
  image_path        TEXT NOT NULL,
  original_filename TEXT NOT NULL DEFAULT '',
  object_key        TEXT NOT NULL DEFAULT '',
  created_at        TEXT NOT NULL DEFAULT app_now()
);

CREATE INDEX IF NOT EXISTS idx_work_logs_master ON work_logs(master_id);
CREATE INDEX IF NOT EXISTS idx_work_logs_status ON work_logs(status);
CREATE INDEX IF NOT EXISTS idx_work_logs_service ON work_logs(service_type);
CREATE INDEX IF NOT EXISTS idx_work_logs_public ON work_logs(is_public, status);
CREATE INDEX IF NOT EXISTS idx_work_images_log ON work_log_images(work_log_id);

-- A username/email can only be claimed once while an application is pending or approved.
CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_pending_username
  ON master_applications(username) WHERE status IN ('pending', 'approved');
CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_pending_email
  ON master_applications(email) WHERE status IN ('pending', 'approved');

-- Session lookups happen on every authenticated request.
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
