-- 003_debt_ledger.sql
-- "Qarz daftari" (debt ledger): financially sensitive records.
--
-- Durability rules for this file:
--   * every statement is IF NOT EXISTS, so re-running it is a no-op;
--   * there is no DROP / TRUNCATE / DELETE, so an existing ledger is never
--     destroyed by a deploy or by re-running migrations;
--   * rows live only in PostgreSQL. Nothing here touches the filesystem, /tmp or
--     any client-side storage, so a Vercel deploy, a cold start, a rebuild or a
--     crash cannot take a debt record with it.
--
-- Money is stored as BIGINT so'm (no cents). REAL would drift on repeated
-- additions, and a ledger that cannot be added up is worthless.

-- ---------------------------------------------------------------------------
-- debts
-- ---------------------------------------------------------------------------
-- `remaining_amount` is a GENERATED column: PostgreSQL derives it from
-- debt_amount - paid_amount on every write, so it is impossible for a stored
-- value to drift from its inputs, and a client-supplied remaining_amount is
-- simply ignored (it is not a column, so it cannot even be inserted).
CREATE TABLE IF NOT EXISTS debts (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name         TEXT NOT NULL,
  phone             TEXT NOT NULL,
  address           TEXT NOT NULL,
  service           TEXT NOT NULL,
  description       TEXT NOT NULL DEFAULT '',
  debt_amount       BIGINT NOT NULL CHECK (debt_amount > 0),
  paid_amount       BIGINT NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
  remaining_amount  BIGINT GENERATED ALWAYS AS (debt_amount - paid_amount) STORED,
  status            TEXT NOT NULL DEFAULT 'unpaid'
                      CHECK (status IN ('unpaid', 'partially_paid', 'paid')),
  created_at        TEXT NOT NULL DEFAULT app_now(),
  updated_at        TEXT NOT NULL DEFAULT app_now(),
  -- Soft delete (see below). NULL means "live"; a timestamp means "archived".
  deleted_at        TEXT,
  deleted_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  -- Kept in sync by the application inside the same transaction that writes a
  -- payment. A CHECK rather than a trigger so it cannot be bypassed: this is the
  -- last line of defence against paid_amount overtaking debt_amount.
  CONSTRAINT debts_paid_not_over_debt CHECK (paid_amount <= debt_amount),
  -- A cleared debt must read as settled, and a debt that still owes money must
  -- not be stored as fully paid. Keeps status consistent with the amounts.
  CONSTRAINT debts_status_matches_amounts CHECK (
    (status = 'paid' AND debt_amount - paid_amount = 0)
    OR (status = 'partially_paid' AND paid_amount > 0 AND debt_amount - paid_amount > 0)
    OR (status = 'unpaid' AND paid_amount = 0)
  )
);

-- ---------------------------------------------------------------------------
-- debt_payments — append-only ledger of every payment ever received.
-- ---------------------------------------------------------------------------
-- Rows are never updated or deleted by the application. `debt_id` is
-- ON DELETE RESTRICT, deliberately: cascading would let a permanent purge take
-- the payment history with it, and a financial ledger that can lose money
-- records is not a ledger. The purge endpoint checks for payments itself and
-- refuses instead, so a debt that ever received money can only be archived, not
-- removed.
CREATE TABLE IF NOT EXISTS debt_payments (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  debt_id     INTEGER NOT NULL REFERENCES debts(id) ON DELETE RESTRICT,
  amount      BIGINT NOT NULL CHECK (amount > 0),
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT app_now(),
  created_by  INTEGER REFERENCES users(id) ON DELETE SET NULL
);

-- ---------------------------------------------------------------------------
-- debt_audit_logs — who did what to which debt, and when.
-- ---------------------------------------------------------------------------
-- `debt_id` is intentionally NOT a foreign key. An audit trail that disappears
-- together with the record it describes is worthless, so the id is stored as a
-- plain BIGINT (no ON DELETE CASCADE anywhere) and `metadata` carries a snapshot
-- of the debtor's identifying fields.
--
-- The pass key is never written here. Deletion is recorded as
-- delete_requested -> deleted, which proves the gate was exercised without ever
-- storing the key itself.
CREATE TABLE IF NOT EXISTS debt_audit_logs (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  debt_id     BIGINT,
  action      TEXT NOT NULL
                CHECK (action IN ('created', 'updated', 'payment_added', 'marked_paid',
                                  'delete_requested', 'delete_denied', 'deleted',
                                  'purged')),
  admin_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  admin_name  TEXT NOT NULL DEFAULT '',
  metadata    TEXT NOT NULL DEFAULT '{}',
  created_at  TEXT NOT NULL DEFAULT app_now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
-- The list view is always "live rows only, newest first", so the composite index
-- at the bottom covers the default query.
--
-- Timestamps are TEXT (app_now() writes a fixed-width 'YYYY-MM-DD HH24:MI:SS'),
-- which is deliberate so the values match the rest of the existing schema. The
-- ordering is only correct because the format is fixed width: lexicographic order
-- equals chronological order for zero-padded Y-M-D H:M:S, so these indexes are
-- usable for ORDER BY as-is.
CREATE INDEX IF NOT EXISTS idx_debts_created_at ON debts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_debts_status ON debts(status);
CREATE INDEX IF NOT EXISTS idx_debts_phone ON debts(phone);
CREATE INDEX IF NOT EXISTS idx_debts_remaining ON debts(remaining_amount DESC);
CREATE INDEX IF NOT EXISTS idx_debts_full_name ON debts(full_name);
CREATE INDEX IF NOT EXISTS idx_debts_service ON debts(service);

-- Covers "live rows, newest first" without touching the table heap.
CREATE INDEX IF NOT EXISTS idx_debts_list ON debts(deleted_at, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_debt_payments_debt ON debt_payments(debt_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_debt_audit_debt ON debt_audit_logs(debt_id);
CREATE INDEX IF NOT EXISTS idx_debt_audit_created ON debt_audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_debt_audit_action ON debt_audit_logs(action);