-- ---------------------------------------------------------------------------
-- 004_inventory — oil and filter warehouse
-- ---------------------------------------------------------------------------
-- Durability rules (identical to 003):
--   * Every statement is idempotent, so parallel Vercel cold starts and repeated
--     runs converge on the same schema. The runner additionally wraps this file
--     in a transaction under a transaction-scoped advisory lock, so two
--     instances can never apply it at the same time.
--   * No DROP TABLE, TRUNCATE or DELETE anywhere. Existing rows -- including the
--     debt ledger from 003 -- are never touched.
--
-- Money and quantities are NUMERIC, never REAL:
--   * `cost_price` is money. REAL silently loses cents and drifts when summed, and
--     a stock ledger that cannot be added up is worthless.
--   * Oil quantities are fractional (4.5 L, 2.75 L), so an integer column cannot
--     hold them. NUMERIC(12,3) is exact, unlike a floating point type.
--   * Every arithmetic step is performed by PostgreSQL, so 28 - 4.5 is exactly
--     23.5 with no accumulated drift.

-- ---------------------------------------------------------------------------
-- inventory_products — one row per oil or filter SKU in the warehouse.
-- ---------------------------------------------------------------------------
-- `unit` is derived from `type` by a CHECK rather than stored as free text, so
-- "oil measured in pieces" cannot be stored. Oil is always litres, filters are
-- always whole pieces.
--
-- `current_quantity` is maintained exclusively by the application, inside the
-- same transaction that appends the matching inventory_movements row. It is not
-- a generated column because a movement can adjust it to an arbitrary absolute
-- value (stock take), which no expression over the movement rows can express
-- without an anchor row. `inventory_movements` plus the reconciliation query in
-- the API is the independent check on it.
CREATE TABLE IF NOT EXISTS inventory_products (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              TEXT NOT NULL CHECK (length(btrim(name)) > 0),
  type              TEXT NOT NULL CHECK (type IN ('oil', 'filter')),
  brand             TEXT NOT NULL DEFAULT '',
  -- Viscosity ("5W-30") only makes sense for oil; filters must leave it empty.
  viscosity         TEXT NOT NULL DEFAULT '',
  unit              TEXT NOT NULL CHECK (unit IN ('liter', 'piece')),
  package_size      NUMERIC(12, 3) NOT NULL DEFAULT 1 CHECK (package_size > 0),
  current_quantity  NUMERIC(12, 3) NOT NULL DEFAULT 0 CHECK (current_quantity >= 0),
  minimum_quantity  NUMERIC(12, 3) NOT NULL DEFAULT 0 CHECK (minimum_quantity >= 0),
  cost_price        NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (cost_price >= 0),
  is_active         INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at        TEXT NOT NULL DEFAULT app_now(),
  updated_at        TEXT NOT NULL DEFAULT app_now(),
  -- Unit has to agree with the type. This is the last line of defence: the API
  -- derives `unit` from `type`, so this can only fire on a hand-written insert.
  CONSTRAINT inventory_products_unit_matches_type CHECK (
    (type = 'oil' AND unit = 'liter' AND btrim(viscosity) <> '')
    OR (type = 'filter' AND unit = 'piece' AND btrim(viscosity) = '')
  )
);

-- ---------------------------------------------------------------------------
-- inventory_movements — append-only ledger of every stock change.
-- ---------------------------------------------------------------------------
-- This table is the source of truth for the product detail view and the history
-- screen. `before_quantity` / `after_quantity` are recorded per row so the
-- history reads as a narrative and a missing row is immediately visible as a gap
-- between one row's `after_quantity` and the next row's `before_quantity`.
--
-- `quantity` is signed: positive for purchases, negative for consumption, and
-- either for adjustments. That makes a single SUM over the column reproduce the
-- current stock, which is exactly the reconciliation the API and tests assert.
--
-- `product_id` is ON DELETE RESTRICT, so a product that has ever moved can never
-- be hard-deleted out from under its own history.
CREATE TABLE IF NOT EXISTS inventory_movements (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id       INTEGER NOT NULL REFERENCES inventory_products(id) ON DELETE RESTRICT,
  movement_type    TEXT NOT NULL
                     CHECK (movement_type IN ('purchase', 'consumption', 'adjustment')),
  quantity         NUMERIC(12, 3) NOT NULL CHECK (quantity <> 0),
  before_quantity  NUMERIC(12, 3) NOT NULL CHECK (before_quantity >= 0),
  after_quantity   NUMERIC(12, 3) NOT NULL CHECK (after_quantity >= 0),
  -- Which record caused this movement: 'work_log', 'manual', 'stocktake'.
  -- NULL means the movement is not tied to another table.
  reference_type   TEXT,
  reference_id     INTEGER,
  admin_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
  note             TEXT NOT NULL DEFAULT '',
  created_at       TEXT NOT NULL DEFAULT app_now(),
  -- after_quantity must be exactly before_quantity + quantity. Without this a
  -- bug could record a movement whose own arithmetic contradicts the stock it
  -- claims to have produced, and the two would silently disagree forever.
  CONSTRAINT inventory_movements_balanced CHECK (after_quantity = before_quantity + quantity),
  CONSTRAINT inventory_movements_reference_paired CHECK (
    (reference_type IS NULL AND reference_id IS NULL)
    OR (reference_type IS NOT NULL AND reference_id IS NOT NULL)
  )
);

-- ---------------------------------------------------------------------------
-- service_materials — oil and filters consumed by a work log.
-- ---------------------------------------------------------------------------
-- This is the link between a completed service and the warehouse. One row per
-- product consumed, pointing at the movement that actually moved the stock, so a
-- work log can be traced to the warehouse and vice versa.
CREATE TABLE IF NOT EXISTS service_materials (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_log_id  INTEGER NOT NULL REFERENCES work_logs(id) ON DELETE CASCADE,
  product_id   INTEGER NOT NULL REFERENCES inventory_products(id) ON DELETE RESTRICT,
  quantity     NUMERIC(12, 3) NOT NULL CHECK (quantity > 0),
  movement_id  INTEGER NOT NULL REFERENCES inventory_movements(id) ON DELETE RESTRICT,
  created_at   TEXT NOT NULL DEFAULT app_now()
);

-- ---------------------------------------------------------------------------
-- inventory_audit_logs — who did what to which product, and when.
-- ---------------------------------------------------------------------------
-- The debt ledger has its own audit table (debt_audit_logs) whose `action` is a
-- fixed CHECK enum, and its helpers are module-private, so neither can be reused
-- here without dropping a constraint. The same shape is therefore repeated for
-- the warehouse rather than bent out of shape.
--
-- `product_id` is deliberately NOT a foreign key: an audit trail that vanishes
-- together with the record it describes is worthless.
CREATE TABLE IF NOT EXISTS inventory_audit_logs (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  INTEGER,
  action      TEXT NOT NULL
                CHECK (action IN ('created', 'updated', 'stock_in', 'consumed',
                                  'adjusted', 'activated', 'deactivated',
                                  'delete_requested', 'delete_denied', 'deleted')),
  admin_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  admin_name  TEXT NOT NULL DEFAULT '',
  metadata    TEXT NOT NULL DEFAULT '{}',
  created_at  TEXT NOT NULL DEFAULT app_now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
-- Products: the list screen filters on type and is_active and sorts by name.
CREATE INDEX IF NOT EXISTS idx_inventory_products_type ON inventory_products(type);
CREATE INDEX IF NOT EXISTS idx_inventory_products_active ON inventory_products(is_active);
CREATE INDEX IF NOT EXISTS idx_inventory_products_name ON inventory_products(lower(name));
-- Partial index for the low-stock screen: it only ever looks at live rows whose
-- stock has fallen to or below their minimum, which is a tiny slice of the table.
CREATE INDEX IF NOT EXISTS idx_inventory_products_low_stock
  ON inventory_products(current_quantity, minimum_quantity) WHERE is_active = 1;

-- Movements: the history screen filters by product, by type and by date, and
-- resolves a reference record.
CREATE INDEX IF NOT EXISTS idx_inventory_movements_product ON inventory_movements(product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_type ON inventory_movements(movement_type);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_created ON inventory_movements(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_reference
  ON inventory_movements(reference_type, reference_id);
-- The reconciliation query (SUM(quantity) per product) scans by product_id only.
CREATE INDEX IF NOT EXISTS idx_inventory_movements_product_sum ON inventory_movements(product_id);

-- Service materials: read by work log, and the "has this product ever been used
-- on a job" guard reads by product.
CREATE INDEX IF NOT EXISTS idx_service_materials_work ON service_materials(work_log_id);
CREATE INDEX IF NOT EXISTS idx_service_materials_product ON service_materials(product_id);

-- Audit: same shape as the debt audit indexes.
CREATE INDEX IF NOT EXISTS idx_inventory_audit_product ON inventory_audit_logs(product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_audit_created ON inventory_audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_audit_action ON inventory_audit_logs(action);